# Generated by Django 2.2.10 on 2022-01-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220111_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='poll',
        ),
        migrations.AddField(
            model_name='poll',
            name='question',
            field=models.ManyToManyField(related_name='polls', to='polls.Question'),
        ),
    ]
