# Generated by Django 2.2.10 on 2022-01-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20220111_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ManyToManyField(related_name='questions', to='polls.Poll'),
        ),
    ]
